---
runner:
  plugin: threaded
  options:
    num_workers: 10
inventory:
    plugin: SimpleInventory
    options:
        host_file: "inventory/hosts_devnet_sb_cml.yml"
        group_file: "inventory/groups.yml"
